///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ea6ee16a-d48b-4658-b6ef-a445baff1e5d")]
    public partial class MyTest2Repository : RepoGenBaseFolder
    {
        static MyTest2Repository instance = new MyTest2Repository();
        MyTest2RepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest2Repository element repository.
        /// </summary>
        [RepositoryFolder("ea6ee16a-d48b-4658-b6ef-a445baff1e5d")]
        public static MyTest2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest2Repository() 
            : base("MyTest2Repository", "/", null, 0, false, "ea6ee16a-d48b-4658-b6ef-a445baff1e5d", ".\\RepositoryImages\\MyTest2Repositoryea6ee16a.rximgres")
        {
            _calculator = new MyTest2RepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ea6ee16a-d48b-4658-b6ef-a445baff1e5d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("fe3d5096-bb63-430f-935e-c07aec1ffc1e")]
        public virtual MyTest2RepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest2RepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("fe3d5096-bb63-430f-935e-c07aec1ffc1e")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num7buttonInfo;
            RepoItemInfo _dividebuttonInfo;
            RepoItemInfo _num3buttonInfo;
            RepoItemInfo _equalbuttonInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "fe3d5096-bb63-430f-935e-c07aec1ffc1e", "")
            {
                _num7buttonInfo = new RepoItemInfo(this, "Num7Button", ".//container[@automationid='NumberPad']/button[@automationid='num7Button']", ".//button[@automationid='num7Button']", 30000, null, "884314d8-287d-42e1-a2cc-c07f1293357d");
                _dividebuttonInfo = new RepoItemInfo(this, "DivideButton", ".//container[@automationid='StandardOperators']/button[@automationid='divideButton']", ".//button[@automationid='divideButton']", 30000, null, "797aa756-5629-4a79-b83e-bc4954ac6bff");
                _num3buttonInfo = new RepoItemInfo(this, "Num3Button", ".//container[@automationid='NumberPad']/button[@automationid='num3Button']", ".//button[@automationid='num3Button']", 30000, null, "edca4623-efff-4457-b1e5-854092ddba70");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", ".//container[@automationid='StandardOperators']/button[@automationid='equalButton']", ".//button[@automationid='equalButton']", 30000, null, "2f522ed7-aabc-45d1-bde4-e7b654ba9996");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fe3d5096-bb63-430f-935e-c07aec1ffc1e")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fe3d5096-bb63-430f-935e-c07aec1ffc1e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num7Button item.
            /// </summary>
            [RepositoryItem("884314d8-287d-42e1-a2cc-c07f1293357d")]
            public virtual Ranorex.Button Num7Button
            {
                get
                {
                    return _num7buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num7Button item info.
            /// </summary>
            [RepositoryItemInfo("884314d8-287d-42e1-a2cc-c07f1293357d")]
            public virtual RepoItemInfo Num7ButtonInfo
            {
                get
                {
                    return _num7buttonInfo;
                }
            }

            /// <summary>
            /// The DivideButton item.
            /// </summary>
            [RepositoryItem("797aa756-5629-4a79-b83e-bc4954ac6bff")]
            public virtual Ranorex.Button DivideButton
            {
                get
                {
                    return _dividebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DivideButton item info.
            /// </summary>
            [RepositoryItemInfo("797aa756-5629-4a79-b83e-bc4954ac6bff")]
            public virtual RepoItemInfo DivideButtonInfo
            {
                get
                {
                    return _dividebuttonInfo;
                }
            }

            /// <summary>
            /// The Num3Button item.
            /// </summary>
            [RepositoryItem("edca4623-efff-4457-b1e5-854092ddba70")]
            public virtual Ranorex.Button Num3Button
            {
                get
                {
                    return _num3buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num3Button item info.
            /// </summary>
            [RepositoryItemInfo("edca4623-efff-4457-b1e5-854092ddba70")]
            public virtual RepoItemInfo Num3ButtonInfo
            {
                get
                {
                    return _num3buttonInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("2f522ed7-aabc-45d1-bde4-e7b654ba9996")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("2f522ed7-aabc-45d1-bde4-e7b654ba9996")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
